# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  create:
    branches: [ "master" ]
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo version $TAG_NAME build ${{ github.sha }}
        go build -race -ldflags "-X main.Bld=${{ github.sha }} -X main.Ver=$TAG_NAME -extldflags '-static'" -o jirrit
        GOOS=windows go build -ldflags "-X main.Bld=${{ github.sha }} -X main.Ver=$TAG_NAME" -o jirrit.exe
        GOOS=darwin go build -ldflags "-X main.Bld=${{ github.sha }} -X main.Ver=$TAG_NAME" -o jirritMac

    - name: Test
      run: |
        go fmt
        go vet
        go test -v ./...
